// buildings.js — Building definitions
// cps = credits/sec, eps = energy/sec, dps = data/sec

export const BUILDINGS = {
  neonSign: {
    id: 'neonSign',
    name: 'Neon Sign',
    desc: 'A flickering advertisement. Draws attention and credits.',
    baseCost: 10,
    scaleFactor: 1.15,
    cps: 0.5,
    eps: 0,
    dps: 0,
    unlockAt: 0,
  },
  dataTerminal: {
    id: 'dataTerminal',
    name: 'Data Terminal',
    desc: 'Public access point. Generates small data streams.',
    baseCost: 50,
    scaleFactor: 1.18,
    cps: 1,
    eps: 0,
    dps: 0.2,
    unlockAt: 25,
  },
  powerRelay: {
    id: 'powerRelay',
    name: 'Power Relay',
    desc: 'Siphons grid energy for your operations.',
    baseCost: 200,
    scaleFactor: 1.20,
    cps: 3,
    eps: 0.5,
    dps: 0,
    unlockAt: 100,
  },
  holoBoard: {
    id: 'holoBoard',
    name: 'Holo Billboard',
    desc: 'Massive holographic ad. Big revenue.',
    baseCost: 1000,
    scaleFactor: 1.22,
    cps: 12,
    eps: 0.2,
    dps: 0.5,
    unlockAt: 500,
  },
  synthLab: {
    id: 'synthLab',
    name: 'Synth Lab',
    desc: 'Underground lab producing digital goods.',
    baseCost: 5000,
    scaleFactor: 1.25,
    cps: 40,
    eps: 2,
    dps: 3,
    unlockAt: 3000,
  },
  skyTower: {
    id: 'skyTower',
    name: 'Sky Tower',
    desc: 'A corporate megastructure. Dominates the skyline.',
    baseCost: 25000,
    scaleFactor: 1.28,
    cps: 150,
    eps: 8,
    dps: 10,
    unlockAt: 15000,
  },
  aiCore: {
    id: 'aiCore',
    name: 'AI Core',
    desc: 'Self-improving intelligence engine. Exponential returns.',
    baseCost: 150000,
    scaleFactor: 1.30,
    cps: 600,
    eps: 30,
    dps: 50,
    unlockAt: 80000,
  },
  orbitalLink: {
    id: 'orbitalLink',
    name: 'Orbital Link',
    desc: 'Satellite uplink. Credits rain from the sky.',
    baseCost: 1000000,
    scaleFactor: 1.32,
    cps: 2500,
    eps: 100,
    dps: 200,
    unlockAt: 500000,
  },
};

// Ordered list for UI rendering
export const BUILDING_ORDER = [
  'neonSign', 'dataTerminal', 'powerRelay', 'holoBoard',
  'synthLab', 'skyTower', 'aiCore', 'orbitalLink',
];
